"""Prompts for SDR agents."""
from .proposal_prompts import DRAFT_WRITER_PROMPT, FACT_CHECKER_PROMPT
from .research_prompts import RESEARCH_LEAD_PROMPT
from .caller_prompts import (
    CALLER_SYSTEM_PROMPT,
    FIRST_MESSAGE,
    OUTREACH_CALLER_AGENT_PROMPT
)
from .classifier_prompts import CONVERSATION_CLASSIFIER_PROMPT

__all__ = [
    'DRAFT_WRITER_PROMPT',
    'FACT_CHECKER_PROMPT',
    'RESEARCH_LEAD_PROMPT',
    'CALLER_SYSTEM_PROMPT',
    'FIRST_MESSAGE',
    'OUTREACH_CALLER_AGENT_PROMPT',
    'CONVERSATION_CLASSIFIER_PROMPT'
]
